import type { LedgerRow, LedgerState } from "./types";
import { priorityTier } from "./ledger";

const STATE_ORDER: LedgerState[] = [
  "verified",
  "in_review",
  "claimed",
  "todo",
  "blocked",
  "regression",
];

const TIER_NAMES: Record<number, string> = {
  0: "Tier 0 — foundations",
  1: "Tier 1 — _helpers.ts port",
  2: "Tier 2 — core utilities + cards",
  3: "Tier 3 — web + tasks",
  4: "Tier 4 — cljs frontend",
};

function countByState(rows: LedgerRow[]): Record<LedgerState, number> {
  const counts: Record<LedgerState, number> = {
    todo: 0,
    claimed: 0,
    in_review: 0,
    verified: 0,
    blocked: 0,
    regression: 0,
  };
  for (const r of rows) counts[r.state]++;
  return counts;
}

function tableRow(cells: string[]): string {
  return `| ${cells.join(" | ")} |`;
}

export function renderStatusMarkdown(
  collapsed: Map<string, LedgerRow>,
  now: Date = new Date(),
): string {
  const rows = [...collapsed.values()];
  const overall = countByState(rows);
  const total = rows.length;
  const verifiedPct = total === 0 ? 0 : Math.round((overall.verified / total) * 1000) / 10;

  const lines: string[] = [];
  lines.push("# Port Verification Status");
  lines.push("");
  lines.push(
    `_Auto-generated by \`src/ts/verification/resume.ts\` at ${now.toISOString()}. Do not hand-edit; rerun the script._`,
  );
  lines.push("");
  lines.push("## Overall");
  lines.push("");
  lines.push(tableRow(["State", "Count"]));
  lines.push(tableRow(["---", "---:"]));
  for (const s of STATE_ORDER) {
    lines.push(tableRow([s, String(overall[s])]));
  }
  lines.push(tableRow(["**total**", String(total)]));
  lines.push(tableRow(["**verified %**", `${verifiedPct}%`]));
  lines.push("");

  // Per-tier breakdown
  lines.push("## By tier");
  lines.push("");
  lines.push(
    tableRow([
      "Tier",
      "todo",
      "claimed",
      "in_review",
      "verified",
      "blocked",
      "regression",
      "total",
    ]),
  );
  lines.push(tableRow(["---", "---:", "---:", "---:", "---:", "---:", "---:", "---:"]));
  const tiers = new Map<number, LedgerRow[]>();
  for (const r of rows) {
    const t = priorityTier(r.source_path);
    const arr = tiers.get(t) ?? [];
    arr.push(r);
    tiers.set(t, arr);
  }
  const sortedTiers = [...tiers.keys()].sort((a, b) => a - b);
  for (const t of sortedTiers) {
    const trows = tiers.get(t);
    if (trows === undefined) continue;
    const c = countByState(trows);
    lines.push(
      tableRow([
        TIER_NAMES[t] ?? `Tier ${t}`,
        String(c.todo),
        String(c.claimed),
        String(c.in_review),
        String(c.verified),
        String(c.blocked),
        String(c.regression),
        String(trows.length),
      ]),
    );
  }
  lines.push("");

  // Recent verifications
  lines.push("## Most-recent verifications (top 15)");
  lines.push("");
  const verified = rows
    .filter((r) => r.state === "verified" && r.verified_at !== null)
    .sort((a, b) => (b.verified_at ?? "").localeCompare(a.verified_at ?? ""))
    .slice(0, 15);
  if (verified.length === 0) {
    lines.push("_(none yet)_");
  } else {
    lines.push(tableRow(["source_path", "verified_at", "loc", "agent_session"]));
    lines.push(tableRow(["---", "---", "---:", "---"]));
    for (const r of verified) {
      lines.push(
        tableRow([
          r.source_path,
          r.verified_at ?? "",
          String(r.source_loc),
          r.agent_session ?? "",
        ]),
      );
    }
  }
  lines.push("");

  // Blocked / regression rows
  lines.push("## Needs attention (blocked + regression)");
  lines.push("");
  const stuck = rows.filter((r) => r.state === "blocked" || r.state === "regression");
  if (stuck.length === 0) {
    lines.push("_(none)_");
  } else {
    lines.push(tableRow(["source_path", "state", "notes"]));
    lines.push(tableRow(["---", "---", "---"]));
    for (const r of stuck) {
      const note =
        r.findings.notes_path !== null
          ? r.findings.notes_path
          : r.findings.behavioral_gaps.join("; ");
      lines.push(tableRow([r.source_path, r.state, note || ""]));
    }
  }
  lines.push("");

  // Oldest still-claimed
  lines.push("## Oldest still-claimed (>60 min)");
  lines.push("");
  const nowMs = now.getTime();
  const oldClaimed = rows
    .filter((r) => r.state === "claimed" && r.claimed_at !== null)
    .filter((r) => nowMs - Date.parse(r.claimed_at ?? "") > 60 * 60 * 1000)
    .sort((a, b) => (a.claimed_at ?? "").localeCompare(b.claimed_at ?? ""));
  if (oldClaimed.length === 0) {
    lines.push("_(none)_");
  } else {
    lines.push(tableRow(["source_path", "claimed_by", "claimed_at"]));
    lines.push(tableRow(["---", "---", "---"]));
    for (const r of oldClaimed) {
      lines.push(
        tableRow([r.source_path, r.claimed_by ?? "", r.claimed_at ?? ""]),
      );
    }
  }
  lines.push("");

  // Verified without tests
  lines.push("## Verified with no associated tests");
  lines.push("");
  const verifiedNoTests = rows.filter(
    (r) => r.state === "verified" && r.ts_test_paths.length === 0,
  );
  if (verifiedNoTests.length === 0) {
    lines.push("_(none — every verified file has at least one test)_");
  } else {
    lines.push(`_${verifiedNoTests.length} file(s)_`);
    lines.push("");
    lines.push(tableRow(["source_path"]));
    lines.push(tableRow(["---"]));
    for (const r of verifiedNoTests.slice(0, 50)) {
      lines.push(tableRow([r.source_path]));
    }
    if (verifiedNoTests.length > 50) {
      lines.push(`_+ ${verifiedNoTests.length - 50} more_`);
    }
  }
  lines.push("");

  return lines.join("\n") + "\n";
}
