// Game module. Mirrors: src/clj/web/game.clj
// Manages game lifecycle: start, leave, rejoin, concede, action, resync,
// watch (spectator), chat, side-swapping, and state/diff broadcasting.

import { Db } from "mongodb";
import {
  getAppState,
  getLobby,
  swapAppState,
  Lobby,
} from "./app_state";
import { chskSend, registerMsgHandler, WSMessage } from "./ws";
import {
  lobbyThread,
  gameThread,
  playerInLobby,
  spectatorInLobby as spectatorInLobbyCheck,
  inLobby,
  firstPlayerInLobby,
  sendLobbyState,
  sendLobbyTing,
  broadcastLobbyList,
  sendLobbyList,
  uidToLobby,
  joinLobby,
  leaveLobby,
  handleSetLastUpdate,
  handleWatchLobby,
  processDeck,
  logDelay,
  checkPassword,
  allowedInLobby,
} from "./lobby";
import { gameStarted } from "./stats";
import { parseCommand } from "../game/core/commands";
import {
  publicDiffs,
  publicStates,
  messageDiffs,
  type PublicDiffs,
  type MessageDiffs,
} from "../game/core/diffs";
import { makeSystemMessage } from "../game/core/say";
import { findLatest } from "../game/core/finding";
import * as main from "../game/main";
import { matchupByKey } from "../jinteki/preconstructed";
import { makeCorpDeck, makeRunnerDeck } from "../jinteki/chimera";
import { sideFromStr } from "../jinteki/utils";

// ---------------------------------------------------------------------------
// Diff serialization / broadcasting
// ---------------------------------------------------------------------------

/**
 * Converts the appropriate diff to JSON for the given user.
 * Mirrors: (game-diff-json uid gameid side corp-spectators runner-spectators diffs)
 */
function gameDiffJson(
  uid: string,
  gameid: string,
  side: string,
  corpSpectators: Record<string, unknown>[],
  runnerSpectators: Record<string, unknown>[],
  diffs: PublicDiffs | MessageDiffs,
): string {
  const diff =
    side === "Corp"
      ? (diffs as PublicDiffs)["corp-diff"]
      : side === "Runner"
        ? (diffs as PublicDiffs)["runner-diff"]
        : corpSpectators.some((p) => (p as any).uid === uid)
          ? (diffs as PublicDiffs)["corp-spect-diff"]
          : runnerSpectators.some((p) => (p as any).uid === uid)
            ? (diffs as PublicDiffs)["runner-spect-diff"]
            : (diffs as PublicDiffs | MessageDiffs)["spect-diff"];

  return JSON.stringify({ gameid, diff });
}

/**
 * Sends diffs generated by public-diffs to all connected clients.
 * Mirrors: (send-state-diffs lobby diffs)
 */
export function sendStateDiffs(
  lobby: Lobby,
  diffs: PublicDiffs | MessageDiffs,
): void {
  const allUsers = [
    ...(lobby.players ?? []),
    ...(lobby.spectators ?? []),
  ];
  const corpSpectators = (lobby["corp-spectators"] ?? []) as Record<string, unknown>[];
  const runnerSpectators = (lobby["runner-spectators"] ?? []) as Record<string, unknown>[];

  for (const user of allUsers) {
    const uid = (user as any).uid as string | undefined;
    if (!uid) continue;
    const side = (user as any).side as string | undefined;
    chskSend(uid, [
      "game/diff",
      gameDiffJson(uid, String(lobby.gameid), side ?? "", corpSpectators, runnerSpectators, diffs),
    ]);
  }
}

// ---------------------------------------------------------------------------
// State update + diff helpers
// ---------------------------------------------------------------------------

/**
 * Updates the old-states atom with the new game state, then sends a :game/diff
 * message to game clients.
 * Mirrors: (update-and-send-diffs! f lobby & args)
 */
export function updateAndSendDiffs<T extends any[]>(

  f: (state: Record<string, unknown>, ...args: T) => void,
  lobby: Lobby,
  ...args: T
): void {
  const state = (lobby as any).state as Record<string, unknown> | undefined;
  if (!state) return;

  const oldState = { ...state };
  f(state, ...args);

  const spectators = (lobby.spectators ?? []).length > 0;
  const corpSpectators = (lobby["corp-spectators"] ?? []).length > 0;
  const runnerSpectators = (lobby["runner-spectators"] ?? []).length > 0;

  const diffs = publicDiffs(oldState, state as any, spectators, corpSpectators, runnerSpectators);

  // Append hist-diff to history
  if (!state.history) (state as any).history = [];
  (state as any).history.push(diffs["hist-diff"]);

  sendStateDiffs(lobby, diffs);
}

// ---------------------------------------------------------------------------
// Message handling (mirrors handle-message-and-send-diffs!)
// ---------------------------------------------------------------------------

/**
 * If the given message is a command, passes through to `updateAndSendDiffs`.
 * Otherwise, adds the message to the log and only diffs the `:log`.
 * Mirrors: (handle-message-and-send-diffs! lobby side user message)
 */
export function handleMessageAndSendDiffs(
  lobby: Lobby,
  side: string | null,
  user: Record<string, unknown> | null,
  message: string,
): void {
  const state = (lobby as any).state as Record<string, unknown> | undefined;
  if (!state) return;

  // Mirror Clojure: (if (= (str/trim message) "null") " null" message)
  const normalizedMessage = message.trim() === "null" ? " null" : message;

  if (side && user && parseCommand(state as any, side, normalizedMessage)) {
    // It's a command – go through full state update + diffs
    updateAndSendDiffs(
      main.handleSay as any,
      lobby,
      side as any,
      user as any,
      normalizedMessage,
    );
  } else {
    // Notification / chat message – only log diff
    const f = side
      ? (main.handleSay as any)
      : (main.handleNotification as any);
    const oldState = { ...state };
    f(state as any, side ?? null, user ?? null, normalizedMessage);
    const diffs = messageDiffs(oldState, state as any);

    if (!state.history) (state as any).history = [];
    (state as any).history.push(diffs["hist-diff"]);
    sendStateDiffs(lobby, diffs);
  }
}

// ---------------------------------------------------------------------------
// State selection helpers (for full-state broadcasts)
// ---------------------------------------------------------------------------

interface PublicStatesResult {
  "corp-state": Record<string, unknown>;
  "runner-state": Record<string, unknown>;
  "spect-state"?: Record<string, unknown>;
  "corp-spect-state"?: Record<string, unknown>;
  "runner-spect-state"?: Record<string, unknown>;
  "hist-state": Record<string, unknown>;
}

/**
 * Select the correct state view for a uid + side.
 * Mirrors: (select-state uid lobby side diffs)
 */
function selectState(
  uid: string,
  lobby: Lobby,
  side: string | undefined,
  diffs: PublicStatesResult,
): string {
  const corpSpectators = (lobby["corp-spectators"] ?? []) as Record<string, unknown>[];
  const runnerSpectators = (lobby["runner-spectators"] ?? []) as Record<string, unknown>[];

  let selected: Record<string, unknown>;
  if (side === "Corp") {
    selected = diffs["corp-state"];
  } else if (side === "Runner") {
    selected = diffs["runner-state"];
  } else if (corpSpectators.some((p) => (p as any).uid === uid)) {
    selected = diffs["corp-spect-state"];
  } else if (runnerSpectators.some((p) => (p as any).uid === uid)) {
    selected = diffs["runner-spect-state"];
  } else {
    selected = diffs["spect-state"];
  }

  return JSON.stringify(selected);
}

/**
 * Sends full states generated by public-states to all connected clients in lobby.
 * Mirrors: (send-state-to-participants event lobby diffs)
 */
function sendStateToParticipants(
  event: string,
  lobby: Lobby,
  diffs: PublicStatesResult,
): void {
  const allUsers = [
    ...(lobby.players ?? []),
    ...(lobby.spectators ?? []),
  ];
  for (const user of allUsers) {
    const uid = (user as any).uid as string | undefined;
    if (!uid) continue;
    const side = (user as any).side as string | undefined;
    chskSend(uid, [event, selectState(uid, lobby, side, diffs)]);
  }
}

/**
 * Sends full states generated by public-states to single client in lobby.
 * Mirrors: (send-state-to-uid! uid event lobby diffs)
 */
function sendStateToUid(
  uid: string,
  event: string,
  lobby: Lobby,
  diffs: PublicStatesResult,
): void {
  const allUsers = [
    ...(lobby.players ?? []),
    ...(lobby.spectators ?? []),
  ];
  const player = allUsers.find((p) => (p as any).uid === uid);
  if (!player) return;
  const side = (player as any).side as string | undefined;
  chskSend(uid, [event, selectState(uid, lobby, side, diffs)]);
}

// ---------------------------------------------------------------------------
// Starter deck detection
// ---------------------------------------------------------------------------

/**
 * Check if a player is using a starter deck.
 * Mirrors: (is-starter-deck? player)
 */
function isStarterDeck(player: Record<string, unknown>): boolean {
  const deck = player.deck as Record<string, unknown> | undefined;
  if (!deck) return false;
  const identity = (deck.identity as Record<string, unknown>) || {};
  const id = identity.title as string | undefined;
  const cards = (deck.cards as Array<{ qty: number }> | undefined) ?? [];
  const cardCnt = cards.reduce((sum, c) => sum + (c.qty ?? 0), 0);

  return (
    (id === "The Syndicate: Profit over Principle" && cardCnt === 34) ||
    (id === "The Catalyst: Convention Breaker" && cardCnt === 30)
  );
}

/**
 * Starter Decks can require 6 or 7 agenda points.
 * Mirrors: (check-for-starter-decks game)
 */
function checkForStarterDecks(game: Lobby): Lobby {
  const format = (game as any).format as string | undefined;
  const players = game.players ?? [];

  if (format === "system-gateway" && players.every(isStarterDeck)) {
    const state = (game as any).state as Record<string, unknown> | undefined;
    if (state) {
      const runner = (state.runner as Record<string, unknown>) || {};
      const corp = (state.corp as Record<string, unknown>) || {};
      runner["agenda-point-req"] = 6;
      corp["agenda-point-req"] = 6;
      state.runner = runner;
      state.corp = corp;
    }
  }
  return game;
}

// ---------------------------------------------------------------------------
// Deck stripping / precon helpers
// ---------------------------------------------------------------------------

/**
 * Strip deck info from a player after game start.
 * Mirrors: (strip-deck player)
 */
function stripDeck(player: Record<string, unknown>): Record<string, unknown> {
  const deck = player.deck as Record<string, unknown> | undefined;
  if (!deck) return player;

  const strippedDeck: Record<string, unknown> = {
    _id: String((deck._id as any) ?? ""),
    identity: (deck.identity as Record<string, unknown>) || {},
    name: deck.name,
  };
  // Keep only title and faction from identity
  const identity = strippedDeck.identity as Record<string, unknown>;
  strippedDeck.identity = {
    title: identity.title,
    faction: identity.faction,
  };

  return { ...player, deck: strippedDeck };
}

/**
 * Map a deck onto a player in the players list.
 * Mirrors: (player-map-deck players uid deck)
 */
function playerMapDeck(
  players: Record<string, unknown>[],
  uid: string,
  deck: Record<string, unknown>,
): Record<string, unknown>[] {
  return players.map((p) =>
    (p as any).uid === uid ? { ...p, deck } : p,
  );
}

/**
 * Get the uid of the player on the given side.
 * Mirrors: (side-player-uid game side)
 */
function sidePlayerUid(game: Lobby, side: string): string | undefined {
  const player = (game.players ?? []).find(
    (p) => (p as any).side === side,
  ) as Record<string, unknown> | undefined;
  return player ? (player as any).uid : undefined;
}

/**
 * Set preconstructed deck for one side.
 * Mirrors: (set-precon-deck game side decklist)
 */
function setPreconDeck(
  game: Lobby,
  side: string,
  decklist: Record<string, unknown>,
): Lobby {
  const uid = sidePlayerUid(game, side);
  if (!uid) return game;

  const deck = processDeck(decklist as any);
  return {
    ...game,
    players: playerMapDeck(game.players ?? [], uid, deck),
  };
}

/**
 * Set preconstructed decks for both sides.
 * Mirrors: (set-precon-match game precon-match)
 */
function setPreconMatch(
  game: Lobby,
  preconMatch: { corp: Record<string, unknown>; runner: Record<string, unknown> },
): Lobby {
  let result = setPreconDeck(game, "Corp", preconMatch.corp);
  result = setPreconDeck(result, "Runner", preconMatch.runner);
  return result;
}

/**
 * Handle preconstructed / chimera deck setup.
 * Mirrors: (handle-precon-decks game)
 */
function handlePreconDecks(game: Lobby): Lobby {
  const precon = (game as any).precon as string | undefined;
  if (precon) {
    const matchup = matchupByKey(precon as any);
    if (matchup) {
      return setPreconMatch(game, {
        corp: matchup.corp as unknown as Record<string, unknown>,
        runner: matchup.runner as unknown as Record<string, unknown>,
      });
    }
  }

  const format = (game as any).format as string | undefined;
  if (format === "chimera") {
    const corpDeck = makeCorpDeck();
    const runnerDeck = makeRunnerDeck();
    return setPreconMatch(game, {
      corp: corpDeck as unknown as Record<string, unknown>,
      runner: runnerDeck as unknown as Record<string, unknown>,
    });
  }

  return game;
}

// ---------------------------------------------------------------------------
// Game start handling
// ---------------------------------------------------------------------------

/**
 * Handle starting a game.
 * Mirrors: (handle-start-game lobbies gameid players now)
 */
function handleStartGame(
  lobbies: Record<string, Lobby>,
  gameid: string,
  players: Record<string, unknown>[],
  now: Date,
): Record<string, Lobby> {
  const lobby = lobbies[gameid];
  if (!lobby) return lobbies;

  // handle-precon-decks
  let game = handlePreconDecks(lobby);

  // merge started, original-players, ending-players, start-date, last-update, state
  game = {
    ...game,
    started: true,
    "original-players": players,
    "ending-players": players,
    "start-date": now,
    "last-update": now,
    // init-game – create the game state from the lobby config.
    // In the full port, this calls game.core.set-up/init-game.
    // For now, delegate to whatever state initialization the lobby already carries.
    state: (game as any).state ?? {},
  };

  // check-for-starter-decks
  game = checkForStarterDecks(game);

  // strip decks
  game = {
    ...game,
    players: (game.players ?? []).map((p: Record<string, unknown>) => stripDeck(p)),
  };

  return { ...lobbies, [gameid]: game };
}

/**
 * Attempt to start a game (first player only).
 * Mirrors: (try-start-game db uid gameid)
 */
export function tryStartGame(db: Db, uid: string, gameid: string): void {
  const lobby = getLobby(gameid);
  if (!lobby) return;

  const first = firstPlayerInLobby(uid, lobby);
  if (!first || lobby.started) return;

  const now = new Date();
  const newAppState = swapAppState((state) => ({
    ...state,
    lobbies: handleStartGame(state.lobbies, gameid, lobby.players ?? [], now),
  }));

  const lobbyExists = newAppState.lobbies[gameid];
  if (lobbyExists) {
    gameStarted(db, lobbyExists as any);
    sendLobbyState(lobbyExists);
    broadcastLobbyList();
    const state = (lobbyExists as any).state;
    if (state) {
      sendStateToParticipants("game/start", lobbyExists, publicStates(state as any));
    }
  }
}

// ---------------------------------------------------------------------------
// WS message handlers
// ---------------------------------------------------------------------------

/** :game/start */
registerMsgHandler("game/start", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const db = ringReq.system?.db as Db | undefined;
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/start";

  lobbyThread(() => {
    const appState = getAppState();
    if (appState["block-game-creation"]) {
      chskSend(uid, [
        "lobby/toast",
        { message: "lobby_creation-paused", type: "error" },
      ]);
    } else if (db && gameid) {
      tryStartGame(db, uid, gameid);
    }
  });
  logDelay(timestamp, id);
});

/** :game/leave */
registerMsgHandler("game/leave", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const db = ringReq.system?.db as Db | undefined;
  const user = ringReq.user ?? {};
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const replyFn = (msg as any).replyFn;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/leave";

  lobbyThread(() => {
    const lobby = getLobby(gameid as string);
    if (!lobby || !inLobby(uid, lobby) || !lobby.started || !(lobby as any).state) return;

    // The game will not exist if this is the last player to leave.
    const lobbyAfter = leaveLobby(db, user, uid, replyFn, lobby);
    if (lobbyAfter) {
      handleMessageAndSendDiffs(
        lobbyAfter,
        null,
        null,
        `${(user as any).username ?? "User"} has left the game.`,
      );
    }
    sendLobbyList(uid);
    broadcastLobbyList();
  });
  logDelay(timestamp, id);
});

/** :game/rejoin */
function uidInLobbyAsOriginalPlayer(uid: string): Lobby | undefined {
  const lobbies = getAppState().lobbies;
  for (const lobby of Object.values(lobbies)) {
    const originalPlayers = (lobby as any)["original-players"] as
      | Record<string, unknown>[]
      | undefined;
    if (originalPlayers?.some((p) => (p as any).uid === uid)) {
      return lobby;
    }
  }
  return undefined;
}

registerMsgHandler("game/rejoin", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const user = ringReq.user ?? {};
  const data = msg.data as Record<string, unknown> | undefined;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/rejoin";

  lobbyThread(() => {
    const lobby = uidInLobbyAsOriginalPlayer(uid);
    if (!lobby) return;

    const originalPlayers = (lobby as any)["original-players"] as
      | Record<string, unknown>[]
      | undefined;
    const originalPlayer = originalPlayers?.find((p) => (p as any).uid === uid);
    if (!originalPlayer) return;

    const players = lobby.players ?? [];
    const othersCount = players.filter((p) => (p as any).uid !== uid).length;
    if (!lobby.started || othersCount >= 2) return;

    const dataWithSide = { ...(data ?? {}), "request-side": "Any Side" };
    const lobbyAfter = joinLobby(user, uid, dataWithSide, undefined, lobby);
    if (lobbyAfter) {
      const state = (lobbyAfter as any).state;
      if (state) {
        sendStateToUid(uid, "game/start", lobbyAfter, publicStates(state as any));
      }
      updateAndSendDiffs(main.handleRejoin as any, lobbyAfter, user as any);
    }
  });
  logDelay(timestamp, id);
});

/** :game/concede */
registerMsgHandler("game/concede", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/concede";

  const lobby = getLobby(gameid as string);
  if (!lobby) return;
  const player = playerInLobby(uid, lobby);
  if (!player) return;

  gameThread(lobby, () => {
    const side = sideFromStr(String((player as any).side ?? ""));
    updateAndSendDiffs(main.handleConcede as any, lobby, side as any);
  });
  logDelay(timestamp, id);
});

/** :game/action */
registerMsgHandler("game/action", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const command = data?.command as string | undefined;
  const args = (data?.args as any[]) ?? [];
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/action";

  const lobby = getLobby(gameid as string);
  if (!lobby) return;

  gameThread(lobby, () => {
    try {
      const state = (lobby as any).state;
      const player = playerInLobby(uid, lobby);
      const spectator = spectatorInLobbyCheck(uid, lobby);

      if (state && player) {
        const oldState = { ...(state as Record<string, unknown>) };
        const side = sideFromStr(String((player as any).side ?? ""));

        try {
          // handle-set-last-update
          swapAppState((appState) => ({
            ...appState,
            lobbies: handleSetLastUpdate(appState.lobbies, gameid as string, uid),
          }));

          updateAndSendDiffs(
            main.handleAction as any,
            lobby,
            side as any,
            command ?? "",
            args,
          );
        } catch (e) {
          // Reset state on error
          const s = lobby as any;
          s.state = oldState;
          throw e;
        }
      } else if (!spectator && command !== "toast") {
        throw new Error("handle-game-action unknown state or side");
      }
      logDelay(timestamp, id);
    } catch (e: any) {
      chskSend(uid, ["game/error"]);

      const state = (lobby as any).state;
      let lastLogs = "unable to fetch log from state";
      if (state) {
        const log = (state.log as Array<{ public?: string; user?: string; text?: string }>) ?? [];
        lastLogs = log
          .filter((entry) => entry.public && entry.user === "__system__")
          .map((entry) => entry.text ?? "")
          .slice(-5)
          .join("\n\t");
      }

      let cardInfo = "";
      if (args.card && state) {
        const card = findLatest(state as any, args.card as any);
        if (card) {
          cardInfo = `\nRelevant Card: ${(card as any).printedTitle ?? (card as any).title}`;
        }
      }

      console.error(
        e,
        `Caught exception\nCommand: ${command} - ${JSON.stringify(args)}${cardInfo}\nLast messages: ${lastLogs}`,
      );
    }
  });
});

/** :game/resync */
registerMsgHandler("game/resync", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/resync";

  const lobby = getLobby(gameid as string);
  if (!lobby) return;

  gameThread(lobby, () => {
    if (!inLobby(uid, lobby)) return;

    const state = (lobby as any).state;
    if (state) {
      sendStateToUid(uid, "game/resync", lobby, publicStates(state as any));
    } else {
      console.error(
        `resync request unknown state\nGameID:${gameid}\nClientID:${uid}\nPlayers:${JSON.stringify(
          (lobby.players ?? []).map((p: any) => ({ uid: p.uid, side: p.side })),
        )}\nSpectators:${JSON.stringify(
          (lobby.spectators ?? []).map((p: any) => ({ uid: p.uid })),
        )}`,
      );
    }
  });
  logDelay(timestamp, id);
});

/** :game/watch */
registerMsgHandler("game/watch", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const user = ringReq.user ?? {};
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const password = data?.password as string | undefined;
  const requestSide = data?.["request-side"] as string | undefined;
  const replyFn = (msg as any).replyFn;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/watch";

  lobbyThread(() => {
    const lobby = getLobby(gameid as string);
    if (!lobby || !allowedInLobby(user, lobby)) return;

    const correctPassword = checkPassword(lobby, user, password);
    const sideText = requestSide ? ` (${requestSide})` : "";
    const watchStr = `${(user as any).username ?? "User"} joined the game as a spectator${sideText}.`;
    const watchMessage = makeSystemMessage(watchStr);

    const newAppState = swapAppState((state) => ({
      ...state,
      lobbies: handleSetLastUpdate(
        handleWatchLobby(
          state.lobbies,
          gameid as string,
          uid,
          user,
          correctPassword,
          watchMessage,
          requestSide,
        ),
        gameid as string,
        uid,
      ),
    }));

    const lobbyExists = newAppState.lobbies[gameid as string];

    if (lobbyExists && spectatorInLobbyCheck(uid, lobbyExists) && allowedInLobby(user, lobbyExists)) {
      sendLobbyState(lobbyExists);
      sendLobbyTing(lobbyExists);
      broadcastLobbyList();
      const state = (lobbyExists as any).state;
      if (state) {
        main.handleNotification(state as any, watchStr);
      }
      if (state) {
        sendStateToUid(uid, "game/start", lobbyExists, publicStates(state as any));
      }
      if (replyFn) replyFn(200);
    } else if (!correctPassword) {
      if (replyFn) replyFn(403);
    } else {
      if (replyFn) replyFn(404);
    }
  });
  logDelay(timestamp, id);
});

/** :game/mute-spectators */
registerMsgHandler("game/mute-spectators", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const user = ringReq.user ?? {};
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/mute-spectators";

  const newAppState = swapAppState((state) => ({
    ...state,
    lobbies: handleSetLastUpdate(
      (function (lobbies: Record<string, Lobby>): Record<string, Lobby> {
        const lobby = lobbies[gameid as string];
        if (!lobby) return lobbies;
        return {
          ...lobbies,
          [gameid as string]: {
            ...lobby,
            "mute-spectators": !(lobby as any)["mute-spectators"],
          },
        };
      })(state.lobbies),
      gameid as string,
      uid,
    ),
  }));

  const lobbyExists = newAppState.lobbies[gameid as string];
  if (!lobbyExists) return;

  const state = (lobbyExists as any).state;
  const muteSpectators = (lobbyExists as any)["mute-spectators"];
  const message = muteSpectators ? "muted" : "unmuted";

  if (state && playerInLobby(uid, lobbyExists)) {
    gameThread(lobbyExists, () => {
      handleMessageAndSendDiffs(
        lobbyExists,
        null,
        null,
        `${(user as any).username ?? "User"} ${message} spectators.`,
      );
      sendLobbyState(lobbyExists);
    });
  }
  logDelay(timestamp, id);
});

/** :game/say */
registerMsgHandler("game/say", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const user = ringReq.user ?? {};
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const text = data?.msg as string | undefined;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/say";

  if (typeof text !== "string") return;

  const newAppState = swapAppState((state) => ({
    ...state,
    lobbies: handleSetLastUpdate(state.lobbies, gameid as string, uid),
  }));

  const lobbyExists = newAppState.lobbies[gameid as string];
  if (!lobbyExists) return;

  const state = (lobbyExists as any).state;
  const muteSpectators = (lobbyExists as any)["mute-spectators"];

  let side: string | null = null;
  const player = playerInLobby(uid, lobbyExists);
  if (player) {
    side = sideFromStr(String((player as any).side ?? ""));
  } else if (!muteSpectators && spectatorInLobbyCheck(uid, lobbyExists)) {
    side = "spectator";
  }

  if (lobbyExists && state && side) {
    gameThread(lobbyExists, () => {
      handleMessageAndSendDiffs(lobbyExists, side, user, text);
    });
  }
  logDelay(timestamp, id);
});

/** :game/typing */
registerMsgHandler("game/typing", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const data = msg.data as Record<string, unknown> | undefined;
  const gameid = data?.gameid as string | undefined;
  const typing = data?.typing;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "game/typing";

  const lobby = getLobby(gameid as string);
  if (!lobby) return;

  gameThread(lobby, () => {
    const state = (lobby as any).state;
    const player = playerInLobby(uid, lobby);
    if (!state || !player) return;

    const players = lobby.players ?? [];
    for (const p of players) {
      const otherUid = (p as any).uid;
      if (otherUid && otherUid !== uid) {
        chskSend(otherUid, ["game/typing", typing]);
      }
    }
  });
  logDelay(timestamp, id);
});

/** :chsk/uidport-close */
registerMsgHandler("chsk/uidport-close", (msg: WSMessage) => {
  const uid = msg.uid as string;
  const ringReq = (msg as any).ringReq ?? {};
  const db = ringReq.system?.db as Db | undefined;
  const user = ringReq.user ?? {};
  const replyFn = (msg as any).replyFn;
  const timestamp = msg.timestamp ?? Date.now();
  const id = msg.id ?? "chsk/uidport-close";

  // Deregister user (mirrors app-state/deregister-user!)
  // app_state.ts handles this separately in ws.ts close handler,
  // but we mirror the Clojure behavior here as well.

  lobbyThread(() => {
    const lobby = uidToLobby(uid);
    if (!lobby || !lobby.started || !(lobby as any).state) {
      broadcastLobbyList();
      if (replyFn) replyFn(true);
      logDelay(timestamp, id);
      return;
    }

    // The game will not exist if this is the last player to leave.
    const lobbyAfter = leaveLobby(db!, user, uid, undefined, lobby);
    if (lobbyAfter) {
      handleMessageAndSendDiffs(
        lobbyAfter,
        null,
        null,
        `${(user as any).username ?? "User"} has left the game.`,
      );
    }
    broadcastLobbyList();
    if (replyFn) replyFn(true);
  });
  logDelay(timestamp, id);
});

// ---------------------------------------------------------------------------
// Side swapping
// ---------------------------------------------------------------------------

/**
 * Returns a new player map with the player's :side set to a new side.
 * Mirrors: (switch-side player)
 */
function switchSide(player: Record<string, unknown>): Record<string, unknown> {
  const side = (player as any).side;
  return {
    ...player,
    side: side === "Corp" ? "Runner" : "Corp",
  };
}

/**
 * Handle swapping sides for an in-progress game.
 * Mirrors: (handle-swap-sides-in-prog lobbies gameid)
 */
function handleSwapSidesInProg(
  lobbies: Record<string, Lobby>,
  gameid: string,
): Record<string, Lobby> {
  const lobby = lobbies[gameid];
  if (!lobby) return lobbies;

  const updated = {
    ...lobby,
    // original-players needs to be updated so that you rejoin the game
    // on the correct side if you leave/rejoin
    "original-players": ((lobby as any)["original-players"] as Record<string, unknown>[] | undefined)
      ?.map(switchSide),
    players: (lobby.players ?? []).map(switchSide),
  };

  return { ...lobbies, [gameid]: updated };
}

/**
 * Switch sides for a lobby (in-progress game).
 * Mirrors: (switch-side-for-lobby gameid)
 */
export function switchSideForLobby(gameid: string): void {
  const lobby = getLobby(gameid);
  if (!lobby) return;

  const state = (lobby as any).state as Record<string, unknown> | undefined;
  if (!state) return;

  const oldRunner = (state.runner as Record<string, unknown>)?.user;
  const oldRunnerOptions = (state.runner as Record<string, unknown>)?.options;

  // Swap runner/corp user and options
  const newState = { ...state };
  const newRunner = {
    ...newState.runner,
    user: (newState.corp as Record<string, unknown>)?.user,
    options: (newState.corp as Record<string, unknown>)?.options,
  };
  const newCorp = {
    ...newState.corp,
    user: oldRunner,
    options: oldRunnerOptions,
  };
  newState.runner = newRunner;
  newState.corp = newCorp;

  lobbyThread(() => {
    const newAppState = swapAppState((appState) => ({
      ...appState,
      lobbies: handleSwapSidesInProg(appState.lobbies, gameid),
    }));

    const lobbyExists = newAppState.lobbies[gameid];
    if (lobbyExists) {
      sendLobbyState(lobbyExists);
      broadcastLobbyList();
    }
  });
}

// ---------------------------------------------------------------------------
// Lobby command: :swap-sides
// Mirrors: (defmethod commands/lobby-command :swap-sides ...)
// The lobby-command dispatch in commands.ts handles this.
// ---------------------------------------------------------------------------
