// Chimera format deck builder.
// Mirrors: src/cljc/jinteki/chimera.cljc

import { isAgenda, isCorp, isIdentity, isRunner } from "../game/core/card";
import type { Card } from "../game/core/card";
import { AllCards } from "./cards";
import type { Counter, Server, Side } from '../types';


export const runnerEconList = new Set<string>([
  "Bravado",
  "Carpe Diem",
  "Clean Getaway",
  "Creative Commission",
  "Day Job",
  "Dirty Laundry",
  "Easy Mark",
  "Guinea Pig",
  "Hot Pursuit",
  "Lucky Find",
  "Moshing",
  "Peace in Our Time",
  "Raindrops Cut Stone",
  "Strike Fund",
  "Sure Gamble",
  "Aesop's Pawnshop",
  "Armitage Codebusting",
  "Bank Job",
  "Beth Kilrain-Chang",
  "Crowdfunding",
  "Daily Casts",
  "DreamNet",
  "Info Bounty",
  "Jackpot!",
  "Liberated Account",
  "No Free Lunch",
  "Open Market",
  "Paladin Poemu",
  "Red Team",
  "Rogue Trading",
  "Security Testing",
  "Side Hustle",
  "Smartware Distributor",
  "Symmetrical Visage",
  "Telework Contract",
  "Tri-maf Contact",
  "Zona Sul Shipping",
  "Bankroll",
  "Fermenter",
  "Rezeki",
  "Tapwrm",
]);

export const runnerBans = new Set<string>([
  "Blackmail",
  "Calling in Favors",
  "Charm Offensive",
  "Data Breach",
  "Diana's Hunt",
  "Direct Access",
  "Employee Strike",
  "Eureka!",
  "Exclusive Party",
  "Exploratory Romp",
  "Fear the Masses",
  "Feint",
  "Government Investigations",
  "Immolation Script",
  "Itinerant Protesters",
  "Leverage",
  "Mars for Martians",
  "Mass Install",
  "Networking",
  "Office Supplies",
  "Paper Tripping",
  "Populist Rally",
  "Power Nap",
  "Rebirth",
  "Reboot",
  "Spree",
  "Surge",
  "Traffic Jam",
  "Uninstall",
  "Watch the World Burn",
  "Acacia",
  "Archives Interface",
  "BMI Buffer",
  "Bookmark",
  "Capstone",
  "Capybara",
  "Deep Red",
  "Dorm Computer",
  "Ekomind",
  "Forger",
  "Friday Chip",
  "Jeitinho",
  "LLDS Processor",
  "MemStrips",
  "Monolith",
  "Mu Safecracker",
  "Muresh Bodysuit",
  "Plascrete Carapace",
  "Public Terminal",
  "Qianju PT",
  "Rabbit Hole",
  "Ramujan-reliant 550 BMI",
  "Recon Drone",
  "Replicator",
  "Security Chip",
  "Titanium Ribs",
  "Unregistered S&W '35",
  "Window",
  "\"Pretty\" Mary da Silva",
  "Activist Support",
  "Adjusted Chronotype",
  "Akshara Sareen",
  "Angel Arena",
  "Assimilator",
  "Avgustina Ivanovskaya",
  "Bazaar",
  "Bio-Modeled Network",
  "Chrome Parlor",
  "Citadel Sanctuary",
  "Cookbook",
  "Counter Surveillance",
  "Crash Space",
  "Daeg, First Net-Cat",
  "Debbie \"Downtown\" Moreira",
  "Decoy",
  "District 99",
  "Donut Taganes",
  "Dr. Lovegood",
  "Environmental Testing",
  "Fester",
  "First Responders",
  "Gene Conditioning Shoppe",
  "Globalsec Security Clearance",
  "Investigative Journalism",
  "Investigator Inez Delgado",
  "Investigator Inez Delgado 2",
  "Investigator Inez Delgado 3",
  "Investigator Inez Delgado 4",
  "Jarogniew Mercs",
  "Keros Mcintyre",
  "Liberated Chela",
  "Motivation",
  "Net Mercur",
  "New Angeles City Hall",
  "Off-Campus Apartment",
  "Order of Sol",
  "Paige Piper",
  "Paparazzi",
  "Power Tap",
  "Public Sympathy",
  "Sacrificial Clone",
  "Shadow Team",
  "Starlight Crusade Funding",
  "Synthetic Blood",
  "Tallie Perrault",
  "The Back",
  "The Nihilist",
  "Thunder Art Gallery",
  "Underworld Contact",
  "Urban Art Vernissage",
  "Valentina Ferreira Carvalho",
  "Virus Breeding Ground",
  "Wasteland",
  "Whistleblower",
  "Wireless Net Pavilion",
  "Blackstone",
  "Crowbar",
  "Dagger",
  "Dai V",
  "Eater",
  "Fawkes",
  "Houdini",
  "Matryoshka",
  "Penrose",
  "Refractor",
  "Sage",
  "Shiv",
  "Spike",
  "Switchblade",
  "Umbrella",
  "Au Revoir",
  "Copycat",
  "Disrupter",
  "Flux Capacitor",
  "Heliamphora",
  "Hivemind",
  "Incubator",
  "Ixodidae",
  "Keyhole",
  "LLDS Energy Regulator",
  "Net Shield",
  "Origami",
  "Panchatantra",
  "Pawn",
  "Plague",
  "Progenitor",
  "Surveillance Network Key",
  "Surveillance Network Key 2",
]);

export const corpBans = new Set<string>([
  "Ad Blitz",
  "Aimor",
  "Ancestral Imager",
  "Anson Rose",
  "Aryabhata Tech",
  "Awakening Center",
  "Back Channels",
  "Backroom Machinations",
  "Bad Times",
  "Bamboo Dome",
  "Big Brother",
  "Bioroid Efficiency Research",
  "Bioroid Work Crew",
  "Blacklist",
  "Bloom",
  "Bloodletter",
  "Bloop",
  "Brain-Taping Warehouse",
  "Broadcast Square",
  "Builder",
  "Bullfrog",
  "Burke Bugs",
  "Business As Usual",
  "Cerebral Static",
  "Cell Portal",
  "Chairman Hiro",
  "ChiLo City Grid",
  "CFC Excavation Contract",
  "Chronos Project",
  "Clyde Van Rite",
  "Cold Site Server",
  "Commercialization",
  "Constellation Protocol",
  "Corporate War",
  "Cyberdex Trial",
  "Dedicated Response Team",
  "Dedication Ceremony",
  "Defective Brainchips",
  "Director Haas",
  "Drone Screen",
  "Early Premiere",
  "Encrypted Portals",
  "Enforced Curfew",
  "Executive Retreat",
  "Fast Break",
  "Firmware Updates",
  "Foxfire",
  "Freelancer",
  "Fumiko Yamamori",
  "Fractal Threat Matrix",
  "Freedom of Information",
  "Gemini",
  "Henry Phillips",
  "Hasty Relocation",
  "Helium-3 Deposit",
  "Hellion Alpha Test",
  "Hollywood Renovation",
  "Howler",
  "Hudson 1.0",
  "Hyoubu Research Facility",
  "Illicit Sales",
  "Improved Protein Source",
  "Improved Tracers",
  "Increased Drop Rates",
  "Ireress",
  "Investigator Inez Delgado A",
  "Investigator Inez Delgado A 2",
  "Lakshmi Smartfabrics",
  "Lt. Todachine 2",
  "Lockdown",
  "Macrophage",
  "Mark Yale",
  "MCA Informant",
  "Medical Breakthrough",
  "Megaprix Qualifier",
  "Merlin",
  "Metamorph",
  "Merger",
  "Midnight-3 Arcology",
  "Midori",
  "Minelayer",
  "Mumbad Construction Co.",
  "Net Analytics",
  "Net Police",
  "Net Quarantine",
  "Net Watchlist",
  "New Construction",
  "NEXT Wave 2",
  "Observe and Destroy",
  "Otoroshi",
  "PAD Factory",
  "Paper Trail",
  "Pachinko",
  "Personality Profiles",
  "Primary Transmission Dish",
  "Priority Construction",
  "Product Recall",
  "Project Ares",
  "Project Wotan",
  "Psychographics",
  "Puppet Master",
  "Ravana 1.0",
  "Rebranding Team",
  "Reconstruction Contract",
  "Regulatory Capture",
  "Remote Data Farm",
  "Research Grant",
  "Restoring Face",
  "Rutherford Grid",
  "Sacrifice",
  "Salvage",
  "Salem's Hospitality",
  "Satellite Grid",
  "Sealed Vault",
  "Searchlight",
  "Self-Destruct Chips",
  "Sentinel Defense Program",
  "Shipment from Kaguya",
  "Shoot the Moon",
  "Signal Jamming",
  "Simone Diego",
  "Snatch and Grab",
  "Space Camp",
  "Storgotic Resonator",
  "Student Loans",
  "Subcontract",
  "Success",
  "Sunset",
  "Superior Cyberwalls",
  "Synth DNA Modification",
  "Test Ground",
  "The Board",
  "The News Now Hour",
  "The Twins",
  "Tori Hanzō",
  "Traffic Accident",
  "Trieste Model Bioroids",
  "Trojan",
  "Tyr's Hand",
  "Tyrant",
  "Underway Grid",
  "Underway Renovation",
  "Upayoga",
  "Vulcan Coverup",
  "Victoria Jenkins",
  "Warden Fatuma",
  "Watchdog",
  "Wendigo",
  "Wetwork Refit",
  "Witness Tampering",
  "Woodcutter",
  "Zed 1.0",
]);

export const etrIce = new Set<string>([
  "Afshar",
  "Bastion",
  "Battlement",
  "Capacitor",
  "Chimera",
  "Enigma",
  "Guard",
  "Hortum",
  "Ice Wall",
  "Magnet",
  "Maskirovka",
  "Meru Mati",
  "NEXT Bronze",
  "NEXT Silver",
  "Palisade",
  "Paper Wall",
  "Ping",
  "Quandary",
  "Quicksand",
  "Rainbow",
  "Sandstone",
  "Seidr Adaptive Barrier",
  "Self-Adapting Code Wall",
  "Spiderweb",
  "Tree Line",
  "Vanilla",
  "Wall of Static",
  "Wraparound",
]);

export const corpEconList = new Set<string>([
  "Adonis Campaign",
  "Anthill Excavation Contract",
  "Capital Investors",
  "Charlotte Caçador",
  "Cohort Guidance Program",
  "Commercial Bankers Group",
  "Daily Quest",
  "GRNDL Refinery",
  "Humanoid Resources",
  "Illegal Arms Factory",
  "Indian Union Stock Exchange",
  "Janaína \"JK\" Dumont Kindelán",
  "Launch Campaign",
  "Long-Term Investment",
  "Marilyn Campaign",
  "Marked Accounts",
  "Melange Mining Corp.",
  "Mental Health Clinic",
  "Mumba Temple",
  "Nanoetching Matrix",
  "NASX",
  "NGO Front",
  "Nico Campaign",
  "Otto Campaign",
  "PAD Campaign",
  "Public Access Plaza",
  "Rashida Jaheem",
  "Refuge Campaign",
  "Regolith Mining License",
  "Roughneck Repair Squad",
  "Tiered Subscription",
  "Ubiquitous Vig",
  "Wall to Wall",
  "Attitude Adjustment",
  "Beanstalk Royalties",
  "Blue Level Clearance",
  "Celebrity Gift",
  "Extract",
  "Government Subsidy",
  "Greasing the Palm",
  "Green Level Clearance",
  "Hansei Review",
  "Hedge Fund",
  "IPO",
  "Lateral Growth",
  "Mindscaping",
  "Nonequivalent Exchange",
  "Paywall Implementation",
  "Peer Review",
  "Petty Cash",
  "Predictive Planogram",
  "Restructure",
  "Sweeps Week",
  "Too Big to Fail",
  "Tranquility Home Grid",
  "Congratulations!",
  "Pop-up Window",
  "Loot Box",
  "Special Offer",
]);

function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

interface CardEntry {
  qty: number;
  card: string;
}

interface ChimeraDeck {
  identity: { title: string; side: string; code: number };
  name: string;
  format: string;
  cards: CardEntry[];
}

export function makeRunnerDeck(): ChimeraDeck {
  const basePrograms = ["Peacock", "Aurora", "Creeper"];
  const baseProgramSet = new Set(basePrograms);

  const runnerCards = Object.values(AllCards).filter(
    (c) => isRunner(c as unknown as Card) && !isIdentity(c as unknown as Card),
  );

  const formatCards = runnerCards.filter(
    (c) => !runnerBans.has(c["title"] as string) && !baseProgramSet.has(c["title"] as string),
  );

  const allEconCards = runnerCards.filter((c) => runnerEconList.has(c["title"] as string));
  const chosenEconCards = shuffle(allEconCards).slice(0, 8);
  const chosenTitles = new Set([
    ...basePrograms,
    ...chosenEconCards.map((c) => c["title"] as string),
  ]);

  const remainingPool = formatCards.filter((c) => !chosenTitles.has(c["title"] as string));
  const remainingCards = shuffle(remainingPool).slice(0, 29);

  const deck = [
    ...basePrograms.map((t) => ({ title: t })),
    ...chosenEconCards,
    ...remainingCards,
  ];

  return {
    identity: { title: "Nova Initiumia: Catalyst & Impetus", side: "Runner", code: 33093 },
    name: "Chimera Runner",
    format: "Chimera",
    cards: deck.map((c) => ({ qty: 1, card: c["title"] as string })),
  };
}

export function makeCorpDeck(): ChimeraDeck {
  const corpCards = Object.values(AllCards).filter((c) => isCorp(c as unknown as Card));

  const formatCards = corpCards.filter(
    (c) => !corpBans.has(c["title"] as string) && !isIdentity(c as unknown as Card),
  );

  // build 20 agenda points
  const allAgendas = shuffle(formatCards.filter((c) => isAgenda(c as unknown as Card)));
  const chosenAgendas: Record<string, unknown>[] = [];
  let totalPoints = 0;
  for (const agenda of allAgendas) {
    const pts = (agenda["agendapoints"] as number) ?? 0;
    if (totalPoints + pts <= 20) {
      chosenAgendas.push(agenda);
      totalPoints += pts;
    }
    if (totalPoints === 20) break;
  }

  const allEconCards = corpCards.filter((c) => corpEconList.has(c["title"] as string));
  const chosenEconCards = shuffle(allEconCards).slice(0, 9);

  const allEtrIce = corpCards.filter((c) => etrIce.has(c["title"] as string));
  const chosenEtrIce = shuffle(allEtrIce).slice(0, 3);

  const usedTitles = new Set([
    ...chosenAgendas.map((c) => c["title"] as string),
    ...chosenEconCards.map((c) => c["title"] as string),
    ...chosenEtrIce.map((c) => c["title"] as string),
  ]);

  const toFill = 49 - (chosenAgendas.length + 9 + 3);
  const remainingPool = formatCards.filter(
    (c) => !usedTitles.has(c["title"] as string) && !isAgenda(c as unknown as Card),
  );
  const remainingCards = shuffle(remainingPool).slice(0, toFill);

  const deck = [...chosenAgendas, ...chosenEconCards, ...chosenEtrIce, ...remainingCards];

  return {
    identity: { title: "Ampère: Cybernetics For Anyone", side: "Corp", code: 33128 },
    name: "Chimera Corp",
    format: "Chimera",
    cards: deck.map((c) => ({ qty: 1, card: c["title"] as string })),
  };
}
