import { matchup, precon, systemGatewayBeginner, systemGatewayIntermediate, worlds2012BenCorps, worlds2012BenRuns, worlds2013JensCorps, worlds2013JensRuns, worlds2014DanDCorps, worlds2014DanDRuns, worlds2015DanDCorps, worlds2015DanDRuns, worlds2016ChrisDyerCorps, worlds2016ChrisDyerRuns, worlds2017JessCorps, worlds2017JessRuns, worlds2018JoeCorps } from './preconstructed_1';
import type { Matchup, MatchupKey } from './preconstructed_1';
import type { Card } from '../types';


const worlds2018JoeRuns: Matchup = matchup(
  ["preconstructed.worlds-2018-b", "Worlds 2018: Chris Dyer (C) vs. Joe Schupp (R)"],
  ["preconstructed.worlds-2018-b-tag", "Chris Dyer (C) vs. Joe Schupp (R)"],
  ["preconstructed.worlds-2018-info", "403(!) players attended worlds in 2018. This is the final worlds championship to be run by FFG. The tournament was held in Minneapolis, MN, USA, and consisted of 9(?) swiss rounds into a top 16 cut. The legal cardpool consisted of cards up to Reign and Reverie"],
  ["preconstructed.worlds-2018-b-ul", "Worlds 2018: Trust the Process vs. Dan D'Argenio KoS Val"],
  precon("Chris Dyer - 2018: Trust the Process", { title: "NBN: Controlling the Message", side: "Corp", code: 11017 }, [
    { qty: 1, card: "15 Minutes" },
    { qty: 3, card: "AR-Enhanced Security" },
    { qty: 3, card: "Global Food Initiative" },
    { qty: 3, card: "Project Beale" },
    { qty: 1, card: "Quantum Predictive Model" },
    { qty: 1, card: "Amani Senai" },
    { qty: 3, card: "Commercial Bankers Group" },
    { qty: 2, card: "Daily Business Show" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Team Sponsorship" },
    { qty: 1, card: "Closed Accounts" },
    { qty: 1, card: "Exchange of Information" },
    { qty: 3, card: "Hard-Hitting News" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 1, card: "Preemptive Action" },
    { qty: 1, card: "Psychographics" },
    { qty: 1, card: "SEA Source" },
    { qty: 2, card: "Calibration Testing" },
    { qty: 3, card: "Mumbad Virtual Tour" },
    { qty: 2, card: "IP Block" },
    { qty: 3, card: "Resistor" },
    { qty: 3, card: "Enigma" },
    { qty: 1, card: "Tollbooth" },
    { qty: 1, card: "Turnpike" },
  ]),
  precon("Joe Schupp - 2018: Dan D'Argenio KoS Val", { title: "Valencia Estevez: The Angel of Cayambe", side: "Runner", code: 7030 }, [
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "Employee Strike" },
    { qty: 3, card: "I've Had Worse" },
    { qty: 2, card: "Indexing" },
    { qty: 3, card: "Inject" },
    { qty: 3, card: "Mining Accident" },
    { qty: 1, card: "Rebirth" },
    { qty: 3, card: "Stimhack" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Turntable" },
    { qty: 3, card: "Daily Casts" },
    { qty: 3, card: "Earthrise Hotel" },
    { qty: 1, card: "Ice Carver" },
    { qty: 3, card: "Liberated Account" },
    { qty: 1, card: "No One Home" },
    { qty: 2, card: "The Turning Wheel" },
    { qty: 2, card: "Aumakua" },
    { qty: 3, card: "Black Orchestra" },
    { qty: 2, card: "MKUltra" },
    { qty: 3, card: "Paperclip" },
    { qty: 1, card: "D4v1d" },
  ])
);

// Worlds 2019: Pinsel vs. Testrunning
const worlds2019PinselCorps: Matchup = matchup(
  ["preconstructed.worlds-2019-a", "Worlds 2019: Pinsel (C) vs. Testrunning (R)"],
  ["preconstructed.worlds-2019-a-tag", "Pinsel (C) vs. Testrunning (R)"],
  ["preconstructed.worlds-2019-info", "256 players played in the first ever Project NISEI Netrunner World Championship in 2019. This tournament was held in Rotterdam, NL, and consisted of 8(?) swiss rounds into a top 16 cut. The legal cardpool consisted of cards up to the Uprising Booster Pack"],
  ["preconstructed.worlds-2019-a-ul", "Worlds 2019: Fully dedicated to efficiency vs. Trash Panda"],
  precon("Pinsel - 2019: Fully dedicated to efficiency", { title: "Asa Group: Security Through Vigilance", side: "Corp", code: 21009 }, [
    { qty: 3, card: "Efficiency Committee" },
    { qty: 3, card: "Global Food Initiative" },
    { qty: 3, card: "Project Vitruvius" },
    { qty: 3, card: "Cybernetics Court" },
    { qty: 2, card: "Executive Boot Camp" },
    { qty: 3, card: "Jeeves Model Bioroids" },
    { qty: 1, card: "Lakshmi Smartfabrics" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 1, card: "Reconstruction Contract" },
    { qty: 2, card: "Archived Memories" },
    { qty: 2, card: "Biotic Labor" },
    { qty: 2, card: "Dedication Ceremony" },
    { qty: 3, card: "Fully Operational" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 3, card: "Violet Level Clearance" },
    { qty: 1, card: "Cyberdex Virus Suite" },
    { qty: 2, card: "Hagen" },
    { qty: 3, card: "Vanilla" },
    { qty: 3, card: "Gatekeeper" },
    { qty: 3, card: "Architect" },
  ]),
  precon("Testrunning - 2019: Trash Panda", { title: "Freedom Khumalo: Crypto-Anarchist", side: "Runner", code: 21081 }, [
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "I've Had Worse" },
    { qty: 3, card: "Inject" },
    { qty: 3, card: "Stimhack" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Clone Chip" },
    { qty: 3, card: "Hippo" },
    { qty: 2, card: "Knobkierie" },
    { qty: 3, card: "Daily Casts" },
    { qty: 3, card: "Liberated Account" },
    { qty: 3, card: "Street Peddler" },
    { qty: 2, card: "Black Orchestra" },
    { qty: 1, card: "MKUltra" },
    { qty: 2, card: "Paperclip" },
    { qty: 2, card: "Yusuf" },
    { qty: 1, card: "Consume" },
    { qty: 2, card: "D4v1d" },
    { qty: 1, card: "Imp" },
    { qty: 1, card: "Pelangi" },
    { qty: 1, card: "Self-modifying Code" },
    { qty: 1, card: "Stargate" },
  ])
);

const worlds2019PinselRuns: Matchup = matchup(
  ["preconstructed.worlds-2019-b", "Worlds 2019: Testrunning (C) vs. Pinsel (R)"],
  ["preconstructed.worlds-2019-b-tag", "Testrunning (C) vs. Pinsel (R)"],
  ["preconstructed.worlds-2019-info", "256 players played in the first ever Project NISEI Netrunner World Championship in 2019. This tournament was held in Rotterdam, NL, and consisted of 8(?) swiss rounds into a top 16 cut. The legal cardpool consisted of cards up to the Uprising Booster Pack"],
  ["preconstructed.worlds-2019-b-ul", "Worlds 2019: 2 Grid for 2 Place vs. Trash Panda"],
  precon("Testrunning - 2019: 2 Grid for 2 Place", { title: "Pālanā Foods: Sustainable Growth", side: "Corp", code: 10030 }, [
    { qty: 3, card: "Nisei MK II" },
    { qty: 3, card: "Obokata Protocol" },
    { qty: 1, card: "Philotic Entanglement" },
    { qty: 1, card: "SSL Endorsement" },
    { qty: 3, card: "NGO Front" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 2, card: "Celebrity Gift" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 3, card: "IPO" },
    { qty: 3, card: "Scarcity of Resources" },
    { qty: 3, card: "Bio Vault" },
    { qty: 1, card: "Cyberdex Virus Suite" },
    { qty: 3, card: "La Costa Grid" },
    { qty: 3, card: "Border Control" },
    { qty: 3, card: "IP Block" },
    { qty: 1, card: "DNA Tracker" },
    { qty: 3, card: "Slot Machine" },
    { qty: 2, card: "Thimblerig" },
    { qty: 2, card: "Excalibur" },
    { qty: 3, card: "Anansi" },
  ]),
  precon("Pinsel - 2019: Trash Panda", { title: "Freedom Khumalo: Crypto-Anarchist", side: "Runner", code: 21081 }, [
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "I've Had Worse" },
    { qty: 3, card: "Inject" },
    { qty: 3, card: "Stimhack" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Clone Chip" },
    { qty: 3, card: "Hippo" },
    { qty: 2, card: "Knobkierie" },
    { qty: 3, card: "Daily Casts" },
    { qty: 3, card: "Liberated Account" },
    { qty: 3, card: "Street Peddler" },
    { qty: 2, card: "Black Orchestra" },
    { qty: 1, card: "MKUltra" },
    { qty: 2, card: "Paperclip" },
    { qty: 2, card: "Yusuf" },
    { qty: 1, card: "Consume" },
    { qty: 2, card: "D4v1d" },
    { qty: 1, card: "Imp" },
    { qty: 1, card: "Pelangi" },
    { qty: 1, card: "Self-modifying Code" },
    { qty: 1, card: "Stargate" },
  ])
);

// Worlds 2020: Limes vs. tf34
const worlds2020LimesCorps: Matchup = matchup(
  ["preconstructed.worlds-2020-a", "Worlds 2020: Limes (C) vs. tf34 (R)"],
  ["preconstructed.worlds-2020-a-tag", "Limes (C) vs. tf34 (R)"],
  ["preconstructed.worlds-2020-info", "294 players played in the first ever online world championship for Netrunner, run by Project NISEI 2020. Due to travel restrictions at the start of the COVID-19 pandemic, this tournament was held online via Jinteki.net, and consisted of 8 swiss rounds on two distinct day-ones, into a top 16 cut. The legal cardpool consisted of cards up to Uprising."],
  ["preconstructed.worlds-2020-a-ul", "Worlds 2020: I don't like this deck vs. Engolo Freedom"],
  precon("Limes - 2020: I don't like this deck", { title: "Sportsmetal: Go Big or Go Home", side: "Corp", code: 22026 }, [
    { qty: 2, card: "False Lead" },
    { qty: 3, card: "Hyperloop Extension" },
    { qty: 3, card: "Megaprix Qualifier" },
    { qty: 3, card: "Project Vacheron" },
    { qty: 3, card: "The Future is Now" },
    { qty: 1, card: "CSR Campaign" },
    { qty: 3, card: "Jeeves Model Bioroids" },
    { qty: 3, card: "Marilyn Campaign" },
    { qty: 3, card: "News Team" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Team Sponsorship" },
    { qty: 3, card: "Archived Memories" },
    { qty: 1, card: "BOOM!" },
    { qty: 2, card: "Fast Break" },
    { qty: 3, card: "Game Changer" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 1, card: "Preemptive Action" },
    { qty: 3, card: "Stock Buy-Back" },
    { qty: 3, card: "Meridian" },
  ]),
  precon("tf34 - 2020: Engolo Freedom", { title: "Freedom Khumalo: Crypto-Anarchist", side: "Runner", code: 21081 }, [
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "I've Had Worse" },
    { qty: 1, card: "Rebirth" },
    { qty: 1, card: "Stimhack" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 1, card: "Boomerang" },
    { qty: 3, card: "Hippo" },
    { qty: 2, card: "Keiko" },
    { qty: 3, card: "Zer0" },
    { qty: 3, card: "Daily Casts" },
    { qty: 3, card: "Liberated Account" },
    { qty: 3, card: "Paladin Poemu" },
    { qty: 3, card: "Street Peddler" },
    { qty: 2, card: "The Turning Wheel" },
    { qty: 1, card: "Trickster Taka" },
    { qty: 1, card: "Virus Breeding Ground" },
    { qty: 2, card: "Aumakua" },
    { qty: 2, card: "Engolo" },
    { qty: 3, card: "Yusuf" },
    { qty: 2, card: "Datasucker" },
  ])
);

const worlds2020LimesRuns: Matchup = matchup(
  ["preconstructed.worlds-2020-b", "Worlds 2020: tf34 (R) vs. Limes (C)"],
  ["preconstructed.worlds-2020-b-tag", "tf34 (R) vs. Limes (C)"],
  ["preconstructed.worlds-2020-info", "294 players played in the first ever online world championship for Netrunner, run by Project NISEI 2020. Due to travel restrictions at the start of the COVID-19 pandemic, this tournament was held online via Jinteki.net, and consisted of 8 swiss rounds on two distinct day-ones, into a top 16 cut. The legal cardpool consisted of cards up to Uprising."],
  ["preconstructed.worlds-2020-b-ul", "Worlds 2020: Malia CTM vs. Imp-pressive Hoshiko"],
  precon("tf34 - 2020: Malia CTM", { title: "NBN: Controlling the Message", side: "Corp", code: 11017 }, [
    { qty: 3, card: "Bellona" },
    { qty: 1, card: "Degree Mill" },
    { qty: 3, card: "Project Beale" },
    { qty: 1, card: "Remastered Edition" },
    { qty: 3, card: "Commercial Bankers Group" },
    { qty: 3, card: "Daily Business Show" },
    { qty: 3, card: "Jeeves Model Bioroids" },
    { qty: 3, card: "Malia Z0L0K4" },
    { qty: 3, card: "Marilyn Campaign" },
    { qty: 3, card: "Mumba Temple" },
    { qty: 1, card: "NASX" },
    { qty: 1, card: "PAD Campaign" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Hard-Hitting News" },
    { qty: 2, card: "Market Forces" },
    { qty: 2, card: "Psychographics" },
    { qty: 2, card: "Mumbad Virtual Tour" },
    { qty: 3, card: "IP Block" },
    { qty: 2, card: "Wraparound" },
    { qty: 2, card: "Enigma" },
    { qty: 1, card: "Tollbooth" },
    { qty: 1, card: "F2P" },
  ]),
  precon("Limes - 2020: Imp-pressive Hoshiko", { title: "Hoshiko Shiro: Untold Protagonist", side: "Runner", code: 26066 }, [
    { qty: 3, card: "Dirty Laundry" },
    { qty: 2, card: "I've Had Worse" },
    { qty: 2, card: "Labor Rights" },
    { qty: 1, card: "Rebirth" },
    { qty: 2, card: "Stimhack" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Friday Chip" },
    { qty: 3, card: "Hippo" },
    { qty: 2, card: "HQ Interface" },
    { qty: 3, card: "Patchwork" },
    { qty: 2, card: "DreamNet" },
    { qty: 3, card: "Liberated Account" },
    { qty: 3, card: "Paladin Poemu" },
    { qty: 3, card: "Black Orchestra" },
    { qty: 2, card: "MKUltra" },
    { qty: 3, card: "Paperclip" },
    { qty: 2, card: "Consume" },
    { qty: 3, card: "Imp" },
    { qty: 1, card: "Stargate" },
  ])
);

// Worlds 2021: Patrick Gower vs. Jonas
const worlds2021PatrickCorps: Matchup = matchup(
  ["preconstructed.worlds-2021-a", "Worlds 2021: Patrick Gower (C) vs. Jonas (R)"],
  ["preconstructed.worlds-2021-a-tag", "Patrick Gower (C) vs. Jonas (R)"],
  ["preconstructed.worlds-2021-info", "201 players played in the second online world championship for Netrunner, run by Project NISEI in 2021. Due to the ongoing disruption caused by the COVID-19 pandemic, this tournament was held online via Jinteki.net, and consisted of 8 swiss rounds on two distinct day-ones, into a top 16 cut. The legal cardpool consisted of cards up to System Gateway."],
  ["preconstructed.worlds-2021-a-ul", "Worlds 2021: 44 Card PD vs. Watch Me Drip, Watch Me Maemi"],
  precon("Patrick Gower - 2021: 44 card PD", { title: "Haas-Bioroid: Precision Design", side: "Corp", code: 30035 }, [
    { qty: 3, card: "Cyberdex Sandbox" },
    { qty: 2, card: "Global Food Initiative" },
    { qty: 1, card: "Luminal Transubstantiation" },
    { qty: 2, card: "Offworld Office" },
    { qty: 3, card: "Advanced Assembly Lines" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 2, card: "Spin Doctor" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 3, card: "Seamless Launch" },
    { qty: 1, card: "Anoetic Void" },
    { qty: 1, card: "Crisium Grid" },
    { qty: 1, card: "Cyberdex Virus Suite" },
    { qty: 2, card: "Manegarm Skunkworks" },
    { qty: 3, card: "Tranquility Home Grid" },
    { qty: 2, card: "Border Control" },
    { qty: 1, card: "Hagen" },
    { qty: 3, card: "Gatekeeper" },
    { qty: 1, card: "Macrophage" },
    { qty: 2, card: "Magnet" },
    { qty: 2, card: "Ansel 1.0" },
    { qty: 3, card: "Drafter" },
  ]),
  precon("Jonas - 2021: Watch Me Drip, Watch Me Maemi", { title: "MaxX: Maximum Punk Rock", side: "Runner", code: 7029 }, [
    { qty: 3, card: "Deuces Wild" },
    { qty: 3, card: "Dirty Laundry" },
    { qty: 1, card: "Falsified Credentials" },
    { qty: 3, card: "I've Had Worse" },
    { qty: 3, card: "Labor Rights" },
    { qty: 3, card: "Mining Accident" },
    { qty: 3, card: "Moshing" },
    { qty: 2, card: "Overclock" },
    { qty: 1, card: "Rebirth" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 3, card: "Gachapon" },
    { qty: 3, card: "Hippo" },
    { qty: 2, card: "Maw" },
    { qty: 2, card: "Zer0" },
    { qty: 1, card: "Citadel Sanctuary" },
    { qty: 3, card: "Daily Casts" },
    { qty: 1, card: "DJ Fenris" },
    { qty: 3, card: "Liberated Account" },
    { qty: 2, card: "Mystic Maemi" },
    { qty: 3, card: "PAD Tap" },
    { qty: 3, card: "Paladin Poemu" },
    { qty: 2, card: "Political Operative" },
    { qty: 1, card: "Trickster Taka" },
    { qty: 3, card: "Black Orchestra" },
    { qty: 3, card: "MKUltra" },
    { qty: 3, card: "Paperclip" },
    { qty: 2, card: "Botulus" },
    { qty: 3, card: "Rezeki" },
    { qty: 2, card: "Stargate" },
  ])
);

const worlds2021PatrickRuns: Matchup = matchup(
  ["preconstructed.worlds-2021-b", "Worlds 2021: Jonas (C) vs. Patrick Gower (R)"],
  ["preconstructed.worlds-2021-b-tag", "Jonas (C) vs. Patrick Gower (R)"],
  ["preconstructed.worlds-2021-info", "201 players played in the second online world championship for Netrunner, run by Project NISEI in 2021. Due to the ongoing disruption caused by the COVID-19 pandemic, this tournament was held online via Jinteki.net, and consisted of 8 swiss rounds on two distinct day-ones, into a top 16 cut. The legal cardpool consisted of cards up to System Gateway."],
  ["preconstructed.worlds-2021-b-ul", "Worlds 2021: Is Gagarin Good? vs. Medium to Large MaxX"],
  precon("Jonas - 2021: Is Gagarin Good?", { title: "Gagarin Deep Space: Expanding the Horizon", side: "Corp", code: 7002 }, [
    { qty: 1, card: "Above the Law" },
    { qty: 2, card: "Global Food Initiative" },
    { qty: 2, card: "Hostile Takeover" },
    { qty: 2, card: "Offworld Office" },
    { qty: 3, card: "Project Atlas" },
    { qty: 3, card: "Commercial Bankers Group" },
    { qty: 3, card: "Jeeves Model Bioroids" },
    { qty: 3, card: "Marilyn Campaign" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Reconstruction Contract" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 3, card: "Wall to Wall" },
    { qty: 1, card: "Audacity" },
    { qty: 1, card: "Consulting Visit" },
    { qty: 3, card: "Dedication Ceremony" },
    { qty: 3, card: "Economic Warfare" },
    { qty: 2, card: "Hard-Hitting News" },
    { qty: 1, card: "High-Profile Target" },
    { qty: 3, card: "Border Control" },
    { qty: 2, card: "Magnet" },
    { qty: 1, card: "Mausolus" },
    { qty: 1, card: "Rototurret" },
  ]),
  precon("Patrick Gower - 2021: Medium to Large MaxX", { title: "MaxX: Maximum Punk Rock", side: "Runner", code: 7029 }, [
    { qty: 3, card: "Deuces Wild" },
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "I've Had Worse" },
    { qty: 3, card: "Labor Rights" },
    { qty: 1, card: "Mad Dash" },
    { qty: 3, card: "Moshing" },
    { qty: 3, card: "Overclock" },
    { qty: 1, card: "Rebirth" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 3, card: "Hippo" },
    { qty: 3, card: "Maw" },
    { qty: 3, card: "Aeneas Informant" },
    { qty: 3, card: "Daily Casts" },
    { qty: 3, card: "Liberated Account" },
    { qty: 3, card: "PAD Tap" },
    { qty: 2, card: "Paladin Poemu" },
    { qty: 1, card: "Political Operative" },
    { qty: 1, card: "Salsette Slums" },
    { qty: 1, card: "The Turning Wheel" },
    { qty: 3, card: "Black Orchestra" },
    { qty: 3, card: "MKUltra" },
    { qty: 3, card: "Paperclip" },
    { qty: 1, card: "Botulus" },
    { qty: 3, card: "Rezeki" },
    { qty: 1, card: "Stargate" },
  ])
);

// Worlds 2022: William Huang vs. skry
const worlds2022SokkaCorps: Matchup = matchup(
  ["preconstructed.worlds-2022-a", "Worlds 2022: William Huang (C) vs. skry (R)"],
  ["preconstructed.worlds-2022-a-tag", "William Huang (C) vs. skry (R)"],
  ["preconstructed.worlds-2022-info", "158 players played in the first world championship run by Null Signal Games (formerly Project NISEI), which was the first Netrunner world championship to be run in-person since the start of the COVID-19 pandemic. The tournament was held in Toronto, Canada, and consisted of 8(?) rounds into a top 16 cut. The legal cardpool consisted of cards up to Midnight Sun."],
  ["preconstructed.worlds-2022-a-ul", "Worlds 2022: SNACS vs. Liberté, Égalité, Humidité"],
  precon("William Huang - 2022: SNACS", { title: "Sportsmetal: Go Big or Go Home", side: "Corp", code: 22026 }, [
    { qty: 1, card: "Élivágar Bifurcation" },
    { qty: 2, card: "Global Food Initiative" },
    { qty: 1, card: "Luminal Transubstantiation" },
    { qty: 3, card: "Megaprix Qualifier" },
    { qty: 1, card: "Offworld Office" },
    { qty: 3, card: "Project Vitruvius" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 2, card: "Audacity" },
    { qty: 2, card: "Biotic Labor" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 3, card: "NEXT Activation Command" },
    { qty: 3, card: "Red Level Clearance" },
    { qty: 3, card: "Seamless Launch" },
    { qty: 2, card: "Mavirus" },
    { qty: 3, card: "Tranquility Home Grid" },
    { qty: 1, card: "Hagen" },
    { qty: 3, card: "Fairchild 3.0" },
    { qty: 3, card: "Magnet" },
    { qty: 1, card: "Loki" },
    { qty: 2, card: "Ansel 1.0" },
    { qty: 1, card: "Drafter" },
  ]),
  precon("skry - 2022: Liberté, Égalité, Humidité", { title: "Freedom Khumalo: Crypto-Anarchist", side: "Runner", code: 21081 }, [
    { qty: 3, card: "Deuces Wild" },
    { qty: 2, card: "Dirty Laundry" },
    { qty: 1, card: "Mad Dash" },
    { qty: 3, card: "Moshing" },
    { qty: 2, card: "Pinhole Threading" },
    { qty: 3, card: "Steelskin Scarring" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Endurance" },
    { qty: 3, card: "Gachapon" },
    { qty: 3, card: "Hippo" },
    { qty: 2, card: "Zer0" },
    { qty: 1, card: "Citadel Sanctuary" },
    { qty: 1, card: "DreamNet" },
    { qty: 1, card: "Liberated Account" },
    { qty: 1, card: "Mystic Maemi" },
    { qty: 2, card: "Paladin Poemu" },
    { qty: 2, card: "Black Orchestra" },
    { qty: 1, card: "MKUltra" },
    { qty: 1, card: "Paperclip" },
    { qty: 2, card: "Yusuf" },
    { qty: 1, card: "Botulus" },
    { qty: 3, card: "Fermenter" },
    { qty: 2, card: "Stargate" },
  ])
);

const worlds2022SokkaRuns: Matchup = matchup(
  ["preconstructed.worlds-2022-b", "Worlds 2022: skry (C) vs. William Huang (R)"],
  ["preconstructed.worlds-2022-b-tag", "skry (C) vs. William Huang (R)"],
  ["preconstructed.worlds-2022-info", "158 players played in the first world championship run by Null Signal Games (formerly Project NISEI), which was the first Netrunner world championship to be run in-person since the start of the COVID-19 pandemic. The tournament was held in Toronto, Canada, and consisted of 8(?) rounds into a top 16 cut. The legal cardpool consisted of cards up to Midnight Sun."],
  ["preconstructed.worlds-2022-b-ul", "Worlds 2022: Dies to Doom Blade vs. ApocoLat"],
  precon("skry - 2022: Dies to Doomblade", { title: "AgInfusion: New Miracles for a New World", side: "Corp", code: 12052 }, [
    { qty: 1, card: "Longevity Serum" },
    { qty: 3, card: "Obokata Protocol" },
    { qty: 3, card: "Send a Message" },
    { qty: 2, card: "NGO Front" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Regolith Mining License" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 2, card: "Trieste Model Bioroids" },
    { qty: 2, card: "Divert Power" },
    { qty: 3, card: "Hansei Review" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 1, card: "Subliminal Messaging" },
    { qty: 2, card: "Bio Vault" },
    { qty: 2, card: "Chiyashi" },
    { qty: 2, card: "DNA Tracker" },
    { qty: 3, card: "Wave" },
    { qty: 1, card: "Konjin" },
    { qty: 1, card: "Loki" },
    { qty: 3, card: "Anansi" },
    { qty: 3, card: "Anemone" },
    { qty: 3, card: "Mlinzi" },
  ]),
  precon("William Huang - 2022: ApocoLat", { title: "Lat: Ethical Freelancer", side: "Runner", code: 26019 }, [
    { qty: 3, card: "Apocalypse" },
    { qty: 3, card: "Creative Commission" },
    { qty: 1, card: "Deuces Wild" },
    { qty: 3, card: "Diesel" },
    { qty: 3, card: "Dirty Laundry" },
    { qty: 2, card: "Into the Depths" },
    { qty: 2, card: "Mad Dash" },
    { qty: 2, card: "Pinhole Threading" },
    { qty: 3, card: "Rigging Up" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 3, card: "Endurance" },
    { qty: 1, card: "Aesop's Pawnshop" },
    { qty: 1, card: "Beth Kilrain-Chang" },
    { qty: 3, card: "Daily Casts" },
    { qty: 3, card: "Stoneship Chart Room" },
    { qty: 2, card: "Telework Contract" },
    { qty: 2, card: "Engolo" },
    { qty: 1, card: "Ika" },
    { qty: 1, card: "Propeller" },
    { qty: 1, card: "Misdirection" },
    { qty: 1, card: "Self-modifying Code" },
    { qty: 1, card: "Stargate" },
  ])
);

// Worlds 2023: William Huang vs. cableCarnage
const worlds2023SokkaCorps: Matchup = matchup(
  ["preconstructed.worlds-2023-a", "Worlds 2023: William Huang (C) vs. cableCarnage (R)"],
  ["preconstructed.worlds-2023-a-tag", "William Huang (C) vs. cableCarnage (R)"],
  ["preconstructed.worlds-2023-info", "254 players played in the second Netrunner world championship run by Null Signal Games. The tournament was held in Barcelona, Spain, and consisted of 8 rounds into a top 16 cut. The legal cardpool consisted of cards up to The Automata Initiative."],
  ["preconstructed.worlds-2023-a-ul", "Worlds 2023: The Worlds Grid vs. sableCarnage"],
  precon("William Huang - 2023: The Worlds Grind", { title: "Weyland Consortium: Built to Last", side: "Corp", code: 30059 }, [
    { qty: 1, card: "Above the Law" },
    { qty: 3, card: "SDS Drone Deployment" },
    { qty: 3, card: "Send a Message" },
    { qty: 2, card: "Clearinghouse" },
    { qty: 3, card: "NGO Front" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 3, card: "Wall to Wall" },
    { qty: 3, card: "Government Subsidy" },
    { qty: 3, card: "Hedge Fund" },
    { qty: 1, card: "Secure and Protect" },
    { qty: 2, card: "Subliminal Messaging" },
    { qty: 1, card: "Trojan Horse" },
    { qty: 3, card: "Bio Vault" },
    { qty: 3, card: "Akhet" },
    { qty: 1, card: "Border Control" },
    { qty: 2, card: "Pharos" },
    { qty: 3, card: "Tree Line" },
    { qty: 2, card: "Hortum" },
    { qty: 2, card: "Mestnichestvo" },
    { qty: 1, card: "Rime" },
    { qty: 1, card: "Sadaka" },
    { qty: 3, card: "Winchester" },
  ]),
  precon("cableCarnage - 2023: sableCarnage", { title: "Nyusha \"Sable\" Sintashta: Symphonic Prodigy", side: "Runner", code: 33011 }, [
    { qty: 1, card: "Bahia Bands" },
    { qty: 3, card: "Bravado" },
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "Diversion of Funds" },
    { qty: 1, card: "Inside Job" },
    { qty: 1, card: "Mutual Favor" },
    { qty: 2, card: "Pinhole Threading" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Boomerang" },
    { qty: 1, card: "Flip Switch" },
    { qty: 2, card: "Hermes" },
    { qty: 1, card: "WAKE Implant v2A-JRJ" },
    { qty: 3, card: "Daily Casts" },
    { qty: 2, card: "Earthrise Hotel" },
    { qty: 2, card: "Info Bounty" },
    { qty: 1, card: "Miss Bones" },
    { qty: 1, card: "Mystic Maemi" },
    { qty: 2, card: "No Free Lunch" },
    { qty: 1, card: "Paladin Poemu" },
    { qty: 3, card: "The Class Act" },
    { qty: 2, card: "The Twinning" },
    { qty: 1, card: "Aumakua" },
    { qty: 1, card: "Curupira" },
    { qty: 1, card: "Echelon" },
    { qty: 1, card: "Unity" },
    { qty: 1, card: "Cezve" },
  ])
);

const worlds2023SokkaRuns: Matchup = matchup(
  ["preconstructed.worlds-2023-b", "Worlds 2023: cableCarnage (C) vs. William Huang (R)"],
  ["preconstructed.worlds-2023-b-tag", "cableCarnage (C) vs. William Huang (R)"],
  ["preconstructed.worlds-2023-info", "254 players played in the second Netrunner world championship run by Null Signal Games. The tournament was held in Barcelona, Spain, and consisted of 8 rounds into a top 16 cut. The legal cardpool consisted of cards up to The Automata Initiative."],
  ["preconstructed.worlds-2023-b-ul", "Worlds 2023: tableCarnage vs. You *do* always come back!"],
  precon("cableCarnage - 2023: tableCarnage", { title: "Near-Earth Hub: Broadcast Center", side: "Corp", code: 6005 }, [
    { qty: 3, card: "Bellona" },
    { qty: 2, card: "Degree Mill" },
    { qty: 3, card: "False Lead" },
    { qty: 1, card: "Tomorrow's Headline" },
    { qty: 3, card: "Behold!" },
    { qty: 2, card: "Chekist Scion" },
    { qty: 3, card: "Federal Fundraising" },
    { qty: 2, card: "Gaslight" },
    { qty: 1, card: "Malia Z0L0K4" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 2, card: "Reaper Function" },
    { qty: 3, card: "Regolith Mining License" },
    { qty: 1, card: "SIU" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 3, card: "Wage Workers" },
    { qty: 2, card: "Attitude Adjustment" },
    { qty: 1, card: "End of the Line" },
    { qty: 2, card: "Hedge Fund" },
    { qty: 1, card: "Mindscaping" },
    { qty: 3, card: "Oppo Research" },
    { qty: 2, card: "Your Digital Life" },
    { qty: 1, card: "Ping" },
    { qty: 1, card: "Virtual Service Agent" },
    { qty: 1, card: "Unsmiling Tsarevna" },
  ]),
  precon("William Huang - 2023: You *do* always come back!", { title: "Hoshiko Shiro: Untold Protagonist", side: "Runner", code: 26066 }, [
    { qty: 2, card: "Diesel" },
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "Moshing" },
    { qty: 3, card: "Raindrops Cut Stone" },
    { qty: 3, card: "Steelskin Scarring" },
    { qty: 3, card: "Strike Fund" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Boomerang" },
    { qty: 2, card: "Maw" },
    { qty: 3, card: "Daily Casts" },
    { qty: 1, card: "DJ Fenris" },
    { qty: 1, card: "Miss Bones" },
    { qty: 1, card: "Mystic Maemi" },
    { qty: 1, card: "Paladin Poemu" },
    { qty: 2, card: "The Twinning" },
    { qty: 3, card: "Tsakhia \"Bankhar\" Gantulga" },
    { qty: 2, card: "Buzzsaw" },
    { qty: 2, card: "Carmen" },
    { qty: 2, card: "Cleaver" },
    { qty: 2, card: "Fermenter" },
    { qty: 1, card: "Leech" },
  ])
);

// Worlds 2024: Alex Boyd vs. Dee Ruttenberg
const worlds2024DeerRuns: Matchup = matchup(
  ["preconstructed.worlds-2024-a", "Worlds 2024: Alex Boyd (C) vs. Dee Ruttenberg (R)"],
  ["preconstructed.worlds-2024-a-tag", "Alex Boyd (C) vs. Dee Ruttenberg (R)"],
  ["preconstructed.worlds-2024-info", "204 players played in the third Netrunner world championship run by Null Signal Games. In this tournament, Alex Boyd AKA Aruzan (Arissana, Reality Plus) won the title of Netrunner World Champion in a final game Against Dee Ruttenberg AKA DeeR (Lat, PE), with Aruzan going entirely undefeated in the top cut. The tournament was held at the San Francisco Embarcadero Waterfront Hotel on 19th and 20th of October, and consisted of 14 rounds of Single-Sided Swiss into a top 16 cut. The legal cardpool consisted of cards up to Rebellion Without Rehearsal."],
  ["preconstructed.worlds-2024-a-ul", "Worlds 2024: Kill R+ vs. Good Stuff Lat"],
  precon("Aruzan - 2024: Kill R+", { title: "NBN: Reality Plus", side: "Corp", code: 30051 }, [
    { qty: 2, card: "Degree Mill" },
    { qty: 1, card: "Oracle Thinktank" },
    { qty: 3, card: "Project Beale" },
    { qty: 1, card: "Tomorrow's Headline" },
    { qty: 3, card: "False Lead" },
    { qty: 1, card: "Orbital Superiority" },
    { qty: 3, card: "Behold!" },
    { qty: 1, card: "Gaslight" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 1, card: "Lady Liberty" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 3, card: "Regolith Mining License" },
    { qty: 3, card: "Ping" },
    { qty: 3, card: "Unsmiling Tsarevna" },
    { qty: 2, card: "Virtual Service Agent" },
    { qty: 3, card: "Oppo Research" },
    { qty: 1, card: "Predictive Planogram" },
    { qty: 2, card: "Your Digital Life" },
    { qty: 1, card: "Sprint" },
    { qty: 2, card: "Mindscaping" },
    { qty: 2, card: "End of the Line" },
    { qty: 1, card: "Pivot" },
    { qty: 2, card: "AMAZE Amusements" },
    { qty: 2, card: "The Holo Man" },
  ]),
  precon("DeeR - 2024: Deep Dive Lat", { title: "Lat: Ethical Freelancer", side: "Runner", code: 26019 }, [
    { qty: 3, card: "Creative Commission" },
    { qty: 2, card: "Deep Dive" },
    { qty: 2, card: "Diesel" },
    { qty: 3, card: "Trick Shot" },
    { qty: 1, card: "Bahia Bands" },
    { qty: 3, card: "Dirty Laundry" },
    { qty: 3, card: "Overclock" },
    { qty: 2, card: "Sure Gamble" },
    { qty: 2, card: "Pinhole Threading" },
    { qty: 3, card: "Simulchip" },
    { qty: 2, card: "Swift" },
    { qty: 1, card: "Echelon" },
    { qty: 1, card: "Euler" },
    { qty: 1, card: "Gauss" },
    { qty: 1, card: "K2CP Turbine" },
    { qty: 1, card: "Paricia" },
    { qty: 1, card: "Propeller" },
    { qty: 3, card: "Self-modifying Code" },
    { qty: 1, card: "Fermenter" },
    { qty: 1, card: "Cupellation" },
    { qty: 1, card: "Revolver" },
    { qty: 1, card: "Dr. Nuka Vrolyck" },
    { qty: 3, card: "Stoneship Chart Room" },
    { qty: 2, card: "Telework Contract" },
    { qty: 1, card: "DJ Fenris" },
  ])
);

const worlds2024DeerCorps: Matchup = matchup(
  ["preconstructed.worlds-2024-b", "Worlds 2024: Dee Ruttenberg (C) vs Alex Boyd (R)"],
  ["preconstructed.worlds-2024-b-tag", "Dee Ruttenberg (C) vs. Alex Boyd (R)"],
  ["preconstructed.worlds-2024-info", "204 players played in the third Netrunner world championship run by Null Signal Games. In this tournament, Alex Boyd AKA Aruzan (Arissana, Reality Plus) won the title of Netrunner World Champion in a final game Against Dee Ruttenberg AKA DeeR (Lat, PE), with Aruzan going entirely undefeated in the top cut. The tournament was held at the San Francisco Embarcadero Waterfront Hotel on 19th and 20th of October, and consisted of 14 rounds of Single-Sided Swiss into a top 16 cut. The legal cardpool consisted of cards up to Rebellion Without Rehearsal."],
  ["preconstructed.worlds-2024-b-ul", "Worlds 2024: Loud PE vs. Deep Dive Arissana"],
  precon("DeeR - 2024: Loud PE", { title: "Jinteki: Personal Evolution", side: "Corp", code: 1067 }, [
    { qty: 1, card: "Blood in the Water" },
    { qty: 3, card: "Fujii Asset Retrieval" },
    { qty: 2, card: "House of Knives" },
    { qty: 2, card: "Hybrid Release" },
    { qty: 2, card: "Regenesis" },
    { qty: 3, card: "Sting!" },
    { qty: 3, card: "Cohort Guidance Program" },
    { qty: 2, card: "Moon Pool" },
    { qty: 3, card: "Prāna Condenser" },
    { qty: 1, card: "Snare!" },
    { qty: 3, card: "Rashida Jaheem" },
    { qty: 1, card: "Wage Workers" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 2, card: "Anansi" },
    { qty: 2, card: "Anemone" },
    { qty: 3, card: "Tatu-Bola" },
    { qty: 3, card: "Vampyronassa" },
    { qty: 2, card: "Data Loop" },
    { qty: 3, card: "Mindscaping" },
    { qty: 1, card: "Hedge Fund" },
    { qty: 1, card: "Mavirus" },
    { qty: 1, card: "Tranquility Home Grid" },
    { qty: 1, card: "The Holo Man" },
    { qty: 1, card: "Crisium Grid" },
  ]),
  precon("Aruzan - 2024: Spree Arissana", { title: "Arissana Rocha Nahu: Street Artist", side: "Runner", code: 34020 }, [
    { qty: 2, card: "Burner" },
    { qty: 3, card: "Creative Commission" },
    { qty: 3, card: "Deep Dive" },
    { qty: 3, card: "Diesel" },
    { qty: 3, card: "Spec Work" },
    { qty: 2, card: "Spree" },
    { qty: 3, card: "Trick Shot" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 2, card: "Pinhole Threading" },
    { qty: 2, card: "Aniccam" },
    { qty: 3, card: "Simulchip" },
    { qty: 1, card: "Coalescence" },
    { qty: 1, card: "Euler" },
    { qty: 1, card: "Gauss" },
    { qty: 1, card: "Ika" },
    { qty: 3, card: "Muse" },
    { qty: 1, card: "Paricia" },
    { qty: 1, card: "Pichação" },
    { qty: 1, card: "Propeller" },
    { qty: 1, card: "Self-modifying Code" },
    { qty: 1, card: "Botulus" },
    { qty: 2, card: "Fermenter" },
    { qty: 1, card: "Physarum Entangler" },
    { qty: 2, card: "Environmental Testing" },
    { qty: 2, card: "Daily Casts" },
    { qty: 1, card: "DJ Fenris" },
    { qty: 1, card: "Hannah \"Wheels\" Pilintra" },
  ])
);

// Worlds 2025: davz131 vs. ZomZraft
const worlds2025ZomzraftRuns: Matchup = matchup(
  ["preconstructed.worlds-2025-a", "Worlds 2025: davz131 (C) vs. ZomZraft (C)"],
  ["preconstructed.worlds-2025-a-tag", "davz131 (R) vs. ZomZraft (C)"],
  ["preconstructed.worlds-2025-info", "361 players played in the fourth Netrunner world championship run by Null Signal Games. In this tournament, ZomZraft (Epiphany, Hoshiko) won the title of Netrunner World Champion in a final game Against davz131 (Au Co, Esa). The tournament was held at Dovecot Studios in Edenburg on the 18th and 19th of October, and consisted of 14 rounds of Single-Sided Swiss into a top 16 cut. The legal cardpool consisted of cards up to Elevation."],
  ["preconstructed.worlds-2025-a-ul", "Worlds 2025: SBT Bytes vs. Vampire"],
  precon("davz131 - 2025: SBT Bytes", { title: "AU Co.: The Gold Standard in Clones", side: "Corp", code: 35046 }, [
    { qty: 3, card: "Fujii Asset Retrieval" },
    { qty: 1, card: "Longevity Serum" },
    { qty: 3, card: "See How They Run" },
    { qty: 3, card: "False Lead" },
    { qty: 3, card: "Bladderwort" },
    { qty: 2, card: "Byte!" },
    { qty: 3, card: "Cohort Guidance Program" },
    { qty: 3, card: "Moon Pool" },
    { qty: 3, card: "Phật Gioan Baotixita" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 3, card: "Anemone" },
    { qty: 1, card: "Diviner" },
    { qty: 1, card: "Phoneutria" },
    { qty: 3, card: "Semak-samun" },
    { qty: 1, card: "Flyswatter" },
    { qty: 3, card: "Hansei Review" },
    { qty: 2, card: "Mindscaping" },
    { qty: 1, card: "Hedge Fund" },
    { qty: 3, card: "Petty Cash" },
    { qty: 2, card: "Oppo Research" },
    { qty: 2, card: "End of the Line" },
  ]),
  precon("ZomZraft - 2025: Vampire", { title: "Hoshiko Shiro: Untold Protagonist", side: "Runner", code: 26066 }, [
    { qty: 3, card: "Steelskin Scarring" },
    { qty: 3, card: "Strike Fund" },
    { qty: 3, card: "The Price" },
    { qty: 1, card: "Ashen Epilogue" },
    { qty: 3, card: "Pinhole Threading" },
    { qty: 1, card: "Illumination" },
    { qty: 3, card: "Bling" },
    { qty: 3, card: "Devil Charm" },
    { qty: 3, card: "Gachapon" },
    { qty: 1, card: "Solidarity Badge" },
    { qty: 1, card: "Buffer Drive" },
    { qty: 3, card: "Simulchip" },
    { qty: 2, card: "Audrey v2" },
    { qty: 3, card: "Botulus" },
    { qty: 3, card: "Chisel" },
    { qty: 3, card: "Fermenter" },
    { qty: 3, card: "Gourmand" },
    { qty: 2, card: "Cookbook" },
    { qty: 1, card: "Fencer Fueno" },
    { qty: 2, card: "Lago Paranoá Shelter" },
    { qty: 2, card: "Paladin Poemu" },
    { qty: 2, card: "The Twinning" },
  ])
);

const worlds2025ZomzraftCorps: Matchup = matchup(
  ["preconstructed.worlds-2025-b", "Worlds 2025: ZomZraft (C) vs davz131 (R)"],
  ["preconstructed.worlds-2025-b-tag", "ZomZraft (C) vs. davz131 (R)"],
  ["preconstructed.worlds-2025-info", "361 players played in the fourth Netrunner world championship run by Null Signal Games. In this tournament, ZomZraft (Epiphany, Hoshiko) won the title of Netrunner World Champion in a final game Against davz131 (Au Co, Esa). The tournament was held at Dovecot Studios in Edenburg on the 18th and 19th of October, and consisted of 14 rounds of Single-Sided Swiss into a top 16 cut. The legal cardpool consisted of cards up to Elevation."],
  ["preconstructed.worlds-2025-b-ul", "Worlds 2025: Constrictor vs. Esâ me, I'm back"],
  precon("ZomZraft - 2025: Constrictor", { title: "Epiphany Analytica: Nations Undivided", side: "Corp", code: 34048 }, [
    { qty: 3, card: "Artificial Cryptocrash" },
    { qty: 2, card: "Freedom of Information" },
    { qty: 3, card: "Stoke the Embers" },
    { qty: 1, card: "Tomorrow's Headline" },
    { qty: 1, card: "Offworld Office" },
    { qty: 3, card: "Balanced Coverage" },
    { qty: 1, card: "Chekist Scion" },
    { qty: 3, card: "Federal Fundraising" },
    { qty: 1, card: "Public Access Plaza" },
    { qty: 3, card: "Spin Doctor" },
    { qty: 3, card: "B-1001" },
    { qty: 2, card: "The Powers That Be" },
    { qty: 1, card: "Wage Workers" },
    { qty: 2, card: "Warm Reception" },
    { qty: 3, card: "Working Prototype" },
    { qty: 1, card: "Mestnichestvo" },
    { qty: 3, card: "Ping" },
    { qty: 1, card: "Starlit Knight" },
    { qty: 3, card: "Virtual Service Agent" },
    { qty: 1, card: "Bigger Picture" },
    { qty: 1, card: "IP Enforcement" },
    { qty: 3, card: "Oppo Research" },
    { qty: 1, card: "Shipment from Vladisibirsk" },
    { qty: 1, card: "Retribution" },
    { qty: 2, card: "The Holo Man" },
  ]),
  precon("davz131 - 2025: Esâ me, I'm back", { title: "Esâ Afontov: Eco-Insurrectionist", side: "Runner", code: 33001 }, [
    { qty: 2, card: "Chastushka" },
    { qty: 2, card: "Finality" },
    { qty: 1, card: "Katorga Breakout" },
    { qty: 3, card: "Raindrops Cut Stone" },
    { qty: 2, card: "Running Hot" },
    { qty: 3, card: "Steelskin Scarring" },
    { qty: 3, card: "Strike Fund" },
    { qty: 3, card: "Wildcat Strike" },
    { qty: 1, card: "Ashen Epilogue" },
    { qty: 3, card: "Sure Gamble" },
    { qty: 1, card: "Pinhole Threading" },
    { qty: 1, card: "Ritual" },
    { qty: 3, card: "Ghosttongue" },
    { qty: 3, card: "Marrow" },
    { qty: 1, card: "Hippocampic Mechanocytes" },
    { qty: 2, card: "Begemot" },
    { qty: 1, card: "Fermenter" },
    { qty: 5, card: "Matryoshka" },
    { qty: 1, card: "Cupellation" },
    { qty: 1, card: "Mystic Maemi" },
    { qty: 3, card: "Dr. Nuka Vrolyck" },
  ])
);

// Utility

export function matchupByKey(key: MatchupKey): Matchup | undefined {
  switch (key) {
    // not indexed
    case "beginner": return systemGatewayBeginner;
    case "intermediate": return systemGatewayIntermediate;
    // indexed
    case "worlds-2012-a": return worlds2012BenCorps;
    case "worlds-2012-b": return worlds2012BenRuns;
    case "worlds-2013-a": return worlds2013JensCorps;
    case "worlds-2013-b": return worlds2013JensRuns;
    case "worlds-2014-a": return worlds2014DanDCorps;
    case "worlds-2014-b": return worlds2014DanDRuns;
    case "worlds-2015-a": return worlds2015DanDCorps;
    case "worlds-2015-b": return worlds2015DanDRuns;
    case "worlds-2016-a": return worlds2016ChrisDyerCorps;
    case "worlds-2016-b": return worlds2016ChrisDyerRuns;
    case "worlds-2017-a": return worlds2017JessCorps;
    case "worlds-2017-b": return worlds2017JessRuns;
    case "worlds-2018-a": return worlds2018JoeCorps;
    case "worlds-2018-b": return worlds2018JoeRuns;
    case "worlds-2019-a": return worlds2019PinselCorps;
    case "worlds-2019-b": return worlds2019PinselRuns;
    case "worlds-2020-a": return worlds2020LimesCorps;
    case "worlds-2020-b": return worlds2020LimesRuns;
    case "worlds-2021-a": return worlds2021PatrickCorps;
    case "worlds-2021-b": return worlds2021PatrickRuns;
    case "worlds-2022-a": return worlds2022SokkaCorps;
    case "worlds-2022-b": return worlds2022SokkaRuns;
    case "worlds-2023-a": return worlds2023SokkaCorps;
    case "worlds-2023-b": return worlds2023SokkaRuns;
    case "worlds-2024-a": return worlds2024DeerRuns;
    case "worlds-2024-b": return worlds2024DeerCorps;
    case "worlds-2025-a": return worlds2025ZomzraftRuns;
    case "worlds-2025-b": return worlds2025ZomzraftCorps;
  }
}

export const allMatchups: Set<MatchupKey> = new Set<MatchupKey>([
  "worlds-2012-a", "worlds-2012-b",
  "worlds-2013-a", "worlds-2013-b",
  "worlds-2014-a", "worlds-2014-b",
  "worlds-2015-a", "worlds-2015-b",
  "worlds-2016-a", "worlds-2016-b",
  "worlds-2017-a", "worlds-2017-b",
  "worlds-2018-a", "worlds-2018-b",
  "worlds-2019-a", "worlds-2019-b",
  "worlds-2020-a", "worlds-2020-b",
  "worlds-2021-a", "worlds-2021-b",
  "worlds-2022-a", "worlds-2022-b",
  "worlds-2023-a", "worlds-2023-b",
  "worlds-2024-a", "worlds-2024-b",
  "worlds-2025-a", "worlds-2025-b",
]);
